/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sessions */
        get: operations["sessions_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description The change feed as Server-Sent Events (lado.server.feed). The position is the
         *     Last-Event-ID header (the browser's own reconnect) or, without it, `after`.
         */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{name}/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agents */
        get: operations["agents_api_sessions__name__agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{name}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Messages
         * @description The session's messages, oldest first; with `with`, only those from and to it
         *     (the human: the chat).
         */
        get: operations["messages_api_sessions__name__messages_get"];
        put?: never;
        /**
         * Write
         * @description The human's text to an agent of the session (default: the supervisor), through
         *     the same queue and delivery as an agent's message.
         */
        post: operations["write_api_sessions__name__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{name}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Events
         * @description What happened to the session's flow runs, oldest first.
         */
        get: operations["run_events_api_sessions__name__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{name}/questions/{question}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer
         * @description The human's answer to an agent's open question: a choice, own words, or both.
         */
        post: operations["answer_api_sessions__name__questions__question__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{name}/questions/{question}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss
         * @description The human dismisses an agent's open question; the agent hears of it.
         */
        post: operations["dismiss_api_sessions__name__questions__question__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{name}/agents/{agent}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History
         * @description The agent's window: its last `lines` lines, for the UI's read-only history, and
         *     whether the agent shows a full-screen program, whose history is inside it.
         */
        get: operations["history_api_sessions__name__agents__agent__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentInfo */
        AgentInfo: {
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Provider */
            provider: string;
            /**
             * Status
             * @enum {string}
             */
            status: "starting" | "busy" | "idle" | "waiting" | "stopped";
            /** Run */
            run: string | null;
            /** Task */
            task: string | null;
        };
        /** Answer */
        Answer: {
            /** Choice */
            choice?: string | null;
            /** Text */
            text?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Ok */
            ok: boolean;
            /** Version */
            version: string;
        };
        /** History */
        History: {
            /** Text */
            text: string;
            /** Alternate */
            alternate: boolean;
        };
        /**
         * MessageInfo
         * @description A message, a question to the human (kind "question") or an answer to one.
         */
        MessageInfo: {
            /** Id */
            id: number;
            /** From */
            from: string;
            /** To */
            to: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "message" | "question";
            /** Summary */
            summary: string;
            /** Body */
            body: string;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "sent" | "delivered" | "read" | "dropped" | "failed";
            /** Choices */
            choices: string[] | null;
            /** Free Answer */
            free_answer: boolean;
            /** Question State */
            question_state: ("open" | "answered" | "dismissed" | "closed") | null;
            /** Answered By */
            answered_by: number | null;
            /** Reply To */
            reply_to: number | null;
            /** Choice */
            choice: string | null;
            /** Reply State */
            reply_state: ("replied" | "missing") | null;
            /** Created At */
            created_at: string;
        };
        /**
         * MessageText
         * @description The human's text from the composer.
         */
        MessageText: {
            /**
             * To
             * @default supervisor
             */
            to: string;
            /** Text */
            text: string;
        };
        /**
         * RunEventInfo
         * @description What happened to a flow run: its start, a transition, a gate, its end.
         */
        RunEventInfo: {
            /** Id */
            id: number;
            /** Run */
            run: string;
            /** Kind */
            kind: string;
            /** Actor */
            actor: string;
            /** Detail */
            detail: string;
            /** Created At */
            created_at: string;
        };
        /** Sent */
        Sent: {
            /** Result */
            result: string;
        };
        /** SessionInfo */
        SessionInfo: {
            /** Name */
            name: string;
            /** Repo */
            repo: string;
            status: components["schemas"]["SessionStatus"];
            /** Agents */
            agents: number;
            waiting: components["schemas"]["Waiting"];
        };
        /**
         * SessionStatus
         * @description Whether a session runs, as `lado ls` and the UI show it.
         * @enum {string}
         */
        SessionStatus: "stopped" | "running" | "tmux_gone" | "loop_down";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Waiting
         * @description What in a session waits for the human: the one definition of "needs you".
         */
        Waiting: {
            /** Gates */
            gates: number;
            /** Questions */
            questions: number;
            /** Agents */
            agents: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    sessions_api_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"][];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: {
                after?: number | null;
            };
            header?: {
                "last-event-id"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agents_api_sessions__name__agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    messages_api_sessions__name__messages_get: {
        parameters: {
            query?: {
                with?: "human" | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_api_sessions__name__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageText"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_sessions__name__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEventInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_api_sessions__name__questions__question__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                question: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Answer"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_api_sessions__name__questions__question__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                question: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_sessions__name__agents__agent__history_get: {
        parameters: {
            query?: {
                lines?: number;
            };
            header?: never;
            path: {
                name: string;
                agent: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["History"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
